In [1]:
import pandas as pd
orders = pd.read_csv('data/olist_orders_dataset.csv')
display(orders.head())
orders.info()

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18 00:00:00
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13 00:00:00
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04 00:00:00
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42,2017-12-15 00:00:00
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2018-02-13 21:18:39,2018-02-13 22:20:29,2018-02-14 19:46:34,2018-02-16 18:17:02,2018-02-26 00:00:00

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 99441 entries, 0 to 99440
Data columns (total 8 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   order_id                       99441 non-null  object
 1   customer_id                    99441 non-null  object
 2   order_status                   99441 non-null  object
 3   order_purchase_timestamp       99441 non-null  object
 4   order_approved_at              99281 non-null  object
 5   order_delivered_carrier_date   97658 non-null  object
 6   order_delivered_customer_date  96476 non-null  object
 7   order_estimated_delivery_date  99441 non-null  object
dtypes: object(8)
memory usage: 6.1+ MB

In [2]:
date_columns = [
    'order_purchase_timestamp', 
    'order_approved_at', 
    'order_delivered_carrier_date', 
    'order_delivered_customer_date', 
    'order_estimated_delivery_date'
]
for col in date_columns:
    orders[col] = pd.to_datetime(orders[col])

orders.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 99441 entries, 0 to 99440
Data columns (total 8 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   order_id                       99441 non-null  object
 1   customer_id                    99441 non-null  object
 2   order_status                   99441 non-null  object
 3   order_purchase_timestamp       99441 non-null  datetime64[ns]
 4   order_approved_at              99281 non-null  datetime64[ns]
 5   order_delivered_carrier_date   97658 non-null  datetime64[ns]
 6   order_delivered_customer_date  96476 non-null  datetime64[ns]
 7   order_estimated_delivery_date  99441 non-null  datetime64[ns]
dtypes: datetime64[ns](5), object(3)
memory usage: 6.1+ MB

In [3]:
print(orders.isnull().sum())

order_id                            0
customer_id                         0
order_status                        0
order_purchase_timestamp            0
order_approved_at                 160
order_delivered_carrier_date     1783
order_delivered_customer_date    2965
order_estimated_delivery_date       0
dtype: int64

In [4]:
orders = orders[orders['order_status'] == 'delivered']
orders.dropna(inplace=True)
print(orders.isnull().sum())
print(f'\nОсталось строк: {len(orders)}')

order_id                         0
customer_id                      0
order_status                     0
order_purchase_timestamp         0
order_approved_at                0
order_delivered_carrier_date     0
order_delivered_customer_date    0
order_estimated_delivery_date    0
dtype: int64

Осталось строк: 96455

In [5]:
customers = pd.read_csv('data/olist_customers_dataset.csv')
display(customers.head())
customers.info()

,customer_id,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state
0,06b8999e2fba1a1fbc88172c00ba8bc7,861eff4711a542e4b93843c6dd7febb0,14409,franca,SP
1,18955e83d337fd6b2def6b18a428ac77,290c77bc529b7ac935b93aa66c333dc3,9790,sao bernardo do campo,SP
2,4e7b3e00288586ebd08712fdd0374a03,060e732b5b29e8181a18229c7b0b2b5e,1151,sao paulo,SP
3,b2b6027bc5c5109e529d4dc6358b12c3,259dac757896d24d7702b9acbbff3f3c,8775,mogi das cruzes,SP
4,4f2d8ab171c80ec8364f7c12e35b23ad,345ecd01c38d18a9036ed96c73b8d066,13056,campinas,SP

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 99441 entries, 0 to 99440
Data columns (total 5 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   customer_id               99441 non-null  object
 1   customer_unique_id        99441 non-null  object
 2   customer_zip_code_prefix  99441 non-null  int64
 3   customer_city             99441 non-null  object
 4   customer_state            99441 non-null  object
dtypes: int64(1), object(4)
memory usage: 3.8+ MB

In [6]:
orders_customers = pd.merge(
    orders,             
    customers,          
    on='customer_id',   
    how='inner'         
)
display(orders_customers.info())
print(f"Строк: {len(orders_customers)}")
print(f"Колонок: {len(orders_customers.columns)}")

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 96455 entries, 0 to 96454
Data columns (total 12 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   order_id                       96455 non-null  object
 1   customer_id                    96455 non-null  object
 2   order_status                   96455 non-null  object
 3   order_purchase_timestamp       96455 non-null  datetime64[ns]
 4   order_approved_at              96455 non-null  datetime64[ns]
 5   order_delivered_carrier_date   96455 non-null  datetime64[ns]
 6   order_delivered_customer_date  96455 non-null  datetime64[ns]
 7   order_estimated_delivery_date  96455 non-null  datetime64[ns]
 8   customer_unique_id             96455 non-null  object
 9   customer_zip_code_prefix       96455 non-null  int64
 10  customer_city                  96455 non-null  object
 11  customer_state                 96455 non-null  object
dtypes: datetime64[ns](5), int64(1), object(6)
memory usage: 8.8+ MB

None

Строк: 96455
Колонок: 12

In [7]:
items = pd.read_csv('data/olist_order_items_dataset.csv')
print("Сырая таблица товаров:")
display(items.head())
full_table = pd.merge(
    orders_customers, 
    items, 
    on='order_id', 
    how='inner'
)
print(f"\nСтрок ДО объединения: {len(orders_customers)}")
print(f"Строк ПОСЛЕ объединения: {len(full_table)}")
print(f"Колонок теперь: {len(full_table.columns)}")

Сырая таблица товаров:

,order_id,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value
0,00010242fe8c5a6d1ba2dd792cb16214,1,4244733e06e7ecb4970a6e2683c13e61,48436dade18ac8b2bce089ec2a041202,2017-09-19 09:45:35,58.90,13.29
1,00018f77f2f0320c557190d7a144bdd3,1,e5f2d52b802189ee658865ca93d83a8f,dd7ddc04e1b6c2c614352b383efe2d36,2017-05-03 11:05:13,239.90,19.93
2,000229ec398224ef6ca0657da4fc703e,1,c777355d18b72b67abbeef9df44fd0fd,5b51032eddd242adc84c38acab88f23d,2018-01-18 14:48:30,199.00,17.87
3,00024acbcdf0a6daa1e931b038114c75,1,7634da152a4610f1595efa32f14722fc,9d7a1d34a5052409006425275ba1c2b4,2018-08-15 10:10:18,12.99,12.79
4,00042b26cf59d7ce69dfabb4e55b4fd9,1,ac6c3623068f30de03045865e4e10089,df560393f3a51e74553ab94004ba5c87,2017-02-13 13:57:51,199.90,18.14

Строк ДО объединения: 96455
Строк ПОСЛЕ объединения: 110173
Колонок теперь: 18

In [8]:
payments = pd.read_csv('data/olist_order_payments_dataset.csv')
print("Сырая таблица оплат:")
display(payments.head())
final_table = pd.merge(
    full_table, 
    payments, 
    on='order_id', 
    how='inner'
)
print(f"\nСтрок ДО объединения с платежами: {len(full_table)}")
print(f"Строк ПОСЛЕ объединения: {len(final_table)}")
print(f"Колонок теперь: {len(final_table.columns)}")

Сырая таблица оплат:

,order_id,payment_sequential,payment_type,payment_installments,payment_value
0,b81ef226f3fe1789b1e8b2acac839d17,1,credit_card,8,99.33
1,a9810da82917af2d9aefd1278f1dcfa0,1,credit_card,1,24.39
2,25e8ea4e93396b6fa0d3dd708e76c1bd,1,credit_card,1,65.71
3,ba78997921bbcdc1373bb41e913ab953,1,credit_card,8,107.78
4,42fdf880ba16b47b59251dd489d4441a,1,credit_card,2,128.45

Строк ДО объединения с платежами: 110173
Строк ПОСЛЕ объединения: 115011
Колонок теперь: 22

In [9]:
import sqlite3
conn = sqlite3.connect('olist_database.db')
final_table.to_sql(
    'ecommerce_data',   
    conn,                
    if_exists='replace', 
    index=False          
)

print("Данные успешно загружены в SQL-базу: olist_database.db")

Данные успешно загружены в SQL-базу: olist_database.db

In [10]:
query = """
SELECT 
    order_id, 
    customer_city, 
    payment_value, 
    order_status 
FROM ecommerce_data 
LIMIT 5;
"""

test_result = pd.read_sql(query, conn)
display(test_result)

                           order_id customer_city  payment_value order_status
0  e481f51cbdc54678b7cc49136f2d6af7     sao paulo          18.12    delivered
1  e481f51cbdc54678b7cc49136f2d6af7     sao paulo           2.00    delivered
2  e481f51cbdc54678b7cc49136f2d6af7     sao paulo          18.59    delivered
3  53cdb2fc8bc7dce0b6741e2150273451     barreiras         141.46    delivered
4  47770eb9100c2d0c44946d9cf07ec65d    vianopolis         179.12    delivered

In [11]:
# Пишем многострочный SQL-запрос
rfm_query = """
SELECT 
    customer_unique_id, MAX(order_purchase_timestamp) AS last_purchase_date, COUNT(DISTINCT order_id) AS frequency, SUM(payment_value) AS monetary
FROM ecommerce_data
GROUP BY customer_unique_id
ORDER BY monetary DESC;
"""
rfm_data = pd.read_sql(rfm_query, conn)

print("Топ 10 наших лучших клиентов:")
display(rfm_data)

Топ 10 наших лучших клиентов:

,customer_unique_id,last_purchase_date,frequency,monetary
0,0a0a92112bd4c708ca5fde585afaa872,2017-09-29 15:24:52,1,109312.64
1,698e1cf81d01a3d389d96145f7fa6df8,2017-08-23 09:22:34,1,45256.00
2,c402f431464c72e27330a67f7b94d4fb,2018-02-22 15:30:41,1,44048.00
3,4007669dec559734d6f53e029e360987,2017-11-24 11:03:35,1,36489.24
4,ef8d54b3797ea4db1d63f0ced6a906e9,2018-04-19 13:54:06,1,30186.00
...,...,...,...,...
93330,6f5b9d1cdccc4d28f0483a612edecacf,2017-09-02 16:05:34,1,11.63
93331,2878e5b88167faab17d4fb83a986d38b,2017-10-29 20:28:51,1,11.63
93332,b33336f46234b24a613ad9064d13106d,2018-06-21 20:29:25,1,10.89
93333,bd06ce0e06ad77a7f681f1a4960a3cc6,2017-09-13 19:13:20,1,10.07
93334,317cfc692e3f86c45c95697c61c853a6,2018-08-25 21:20:50,1,9.59

In [12]:
import datetime

rfm_data['last_purchase_date'] = pd.to_datetime(rfm_data['last_purchase_date'])
snapshot_date = rfm_data['last_purchase_date'].max() + datetime.timedelta(days=1)

print(f"Дата отсчета для нашего анализа (Snapshot Date): {snapshot_date}\n")

rfm_data['recency'] = (snapshot_date - rfm_data['last_purchase_date']).dt.days

print("Готовая RFM-таблица (первые 5 клиентов):")
display(rfm_data[['customer_unique_id', 'recency', 'frequency', 'monetary']].head())

Дата отсчета для нашего анализа (Snapshot Date): 2018-08-30 15:00:37

Готовая RFM-таблица (первые 5 клиентов):

                 customer_unique_id  recency  frequency   monetary
0  0a0a92112bd4c708ca5fde585afaa872      334          1  109312.64
1  698e1cf81d01a3d389d96145f7fa6df8      372          1   45256.00
2  c402f431464c72e27330a67f7b94d4fb      188          1   44048.00
3  4007669dec559734d6f53e029e360987      279          1   36489.24
4  ef8d54b3797ea4db1d63f0ced6a906e9      133          1   30186.00

In [13]:
r_labels = [5, 4, 3, 2, 1] 
rfm_data['R_Score'] = pd.qcut(rfm_data['recency'], q=5, labels=r_labels)

m_labels = [1, 2, 3, 4, 5]
rfm_data['M_Score'] = pd.qcut(rfm_data['monetary'], q=5, labels=m_labels)

def get_f_score(x):
    if x == 1:
        return 1
    elif x == 2:
        return 2
    elif x == 3:
        return 3
    elif x == 4:
        return 4
    else:
        return 5

rfm_data['F_Score'] = rfm_data['frequency'].apply(get_f_score)
rfm_data['RFM_Segment'] = rfm_data['R_Score'].astype(str) + rfm_data['F_Score'].astype(str) + rfm_data['M_Score'].astype(str)
rfm_data['RFM_Total_Score'] = rfm_data['R_Score'].astype(int) + rfm_data['F_Score'].astype(int) + rfm_data['M_Score'].astype(int)

print("Финальная RFM-таблица:")
display(rfm_data.head(10))

Финальная RFM-таблица:

,customer_unique_id,last_purchase_date,frequency,monetary,recency,R_Score,M_Score,F_Score,RFM_Segment,RFM_Total_Score
0,0a0a92112bd4c708ca5fde585afaa872,2017-09-29 15:24:52,1,109312.64,334,2,5,1,215,8
1,698e1cf81d01a3d389d96145f7fa6df8,2017-08-23 09:22:34,1,45256.00,372,2,5,1,215,8
2,c402f431464c72e27330a67f7b94d4fb,2018-02-22 15:30:41,1,44048.00,188,3,5,1,315,9
3,4007669dec559734d6f53e029e360987,2017-11-24 11:03:35,1,36489.24,279,2,5,1,215,8
4,ef8d54b3797ea4db1d63f0ced6a906e9,2018-04-19 13:54:06,1,30186.00,133,4,5,1,415,10
5,763c8b1c9c68a0229c42c9fc6f662b93,2018-07-15 14:49:44,1,29099.52,46,5,5,1,515,11
6,c8460e4251689ba205045f3ea17884a1,2018-08-08 14:27:15,4,27935.46,22,5,5,4,545,14
7,eae0a83d752b1dd32697e0e7b4221656,2018-04-24 17:06:54,2,25051.89,127,4,5,2,425,11
8,3d47f4368ccc8e1bb4c4a12dbda7111b,2017-10-02 15:49:23,1,22346.60,331,2,5,1,215,8
9,adfa1cab2b2c8706db21bb13c0a1beb1,2018-06-01 19:08:41,1,19457.04,89,5,5,1,515,11

In [14]:
rfm_data.to_csv('data/rfm_segments_final.csv', index=False)
print("Файл rfm_segments_final.csv успешно создан и сохранен в папке data.")

Файл rfm_segments_final.csv успешно создан и сохранен в папке data.